### ISSUE TITLE
APP for Linux and Mac

### ISSUE THREAD

**Issue by gvsurenderreddy** [supunlakmal/thismypc#76]
Hello sir app for Linux 32 bit and 64 and MAC os .How can i download it please

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by supunlakmal** [comment]
Hi @gvsurenderreddy,
Thanks for reaching out.  Currently, I'm working on windows platform because I did not have resources to test this app with Linux and Mac. It gets a bit time to test,  till that you are welcome to test it on Linux and Mac.

For Electron App `npm run start` will get you to the app interface with debug mode.
You can get more information from - https://github.com/electron-userland/electron-packager

Thanks,
 Supun
